language: node_js
node_js:
  - 'node'

script:
  - npm run build

deploy:
  provider: pages
  github_token: $GITHUB_TOKEN
  local_dir: docs
  skip_cleanup: true
  repo: mikaelbr/kodesnutt-demo-static-host
  on:
    branch: master
  target_branch: master
